# Generated by Django 6.1.1 on 2026-09-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_date_joined_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس کامل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profiles/avatars/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, verbose_name='درباره من'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام نمایشی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=11, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='استان'),
        ),
    ]
