# Generated by Django 6.1.1 on 2026-10-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_address_profile_avatar_profile_biography_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('code_hash', models.CharField(max_length=128, verbose_name='هش کد تایید')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
    ]
