"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party — پکیج‌های خارجی
    'rest_framework',               # Django REST Framework: تبدیل جنگو به API ساز
    'rest_framework_simplejwt',     # JWT: سیستم توکن برای احراز هویت

    # Internal — اپ‌های خودمون
    'accounts.apps.AccountsConfig',
    'catalog.apps.CatalogConfig',
]
AUTH_USER_MODEL = 'accounts.User'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# ──────────────────────────────────────────────────────────────
# Django REST Framework تنظیمات
# ──────────────────────────────────────────────────────────────
# این بخش به DRF میگه:
# ۱) DEFAULT_AUTHENTICATION_CLASSES: چطور بفهمه کاربر کیه؟
#    - JWTAuthentication: توکن JWT رو از هدر Authorization میخونه
#    - SessionAuthentication: کوکی session رو چک میکنه (برای admin و browsable API)
# ۲) DEFAULT_PERMISSION_CLASSES: چه کسی اجازه دسترسی داره؟
#    - AllowAny: همه میتونن (بعداً توی هر ویو جداگانه محدود میکنیم)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# ──────────────────────────────────────────────────────────────
# Simple JWT تنظیمات
# ──────────────────────────────────────────────────────────────
# ACCESS_TOKEN_LIFETIME: عمر توکن دسترسی (۳۰ دقیقه)
#   → هر ۳۰ دقیقه کاربر باید توکن جدید بگیره
# REFRESH_TOKEN_LIFETIME: عمر توکن رفرش (۷ روز)
#   → با این توکن میشه access token جدید گرفت بدون لاگین دوباره
# ROTATE_REFRESH_TOKENS: هر بار رفرش، توکن رفرش جدید هم بده
# BLACKLIST_AFTER_ROTATION: توکن رفرش قبلی رو باطل کن (امنیت بالاتر)

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ──────────────────────────────────────────────────────────────
# Cache تنظیمات — ذخیره‌سازی موقت (برای OTP)
# ──────────────────────────────────────────────────────────────
# LocMemCache: کش توی حافظه RAM سرور
# → برای development عالیه
# → وقتی Redis نصب کردی فقط BACKEND رو عوض میکنی:
#   'django.core.cache.backends.redis.RedisCache'
#   و LOCATION رو میذاری: 'redis://127.0.0.1:6379/1'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'otp-cache',
    }
}

# ──────────────────────────────────────────────────────────────
# OTP تنظیمات — کد یکبار مصرف
# ──────────────────────────────────────────────────────────────
# OTP_EXPIRE_SECONDS: کد بعد از چند ثانیه منقضی بشه (۱۲۰ = ۲ دقیقه)
# OTP_MAX_ATTEMPTS: حداکثر چند بار میتونه کد اشتباه بزنه
# OTP_COOLDOWN_SECONDS: بین دو بار ارسال کد چند ثانیه صبر کنه
# OTP_CODE_LENGTH: طول کد OTP (۵ رقم)

OTP_EXPIRE_SECONDS = 120
OTP_MAX_ATTEMPTS = 3
OTP_COOLDOWN_SECONDS = 60
OTP_CODE_LENGTH = 5
