# Generated by Django 6.1.1 on 2026-10-01 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('retail_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت خرده فروشی')),
                ('wholesale_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت عمده فروشی')),
                ('retail_available', models.BooleanField(default=True, verbose_name='فروش خرده مجاز')),
                ('retail_min_quantity', models.PositiveIntegerField(default=1, verbose_name='حداقل تعداد خرید خرده')),
                ('retail_max_quantity', models.PositiveIntegerField(default=6, verbose_name='حداکثر تعداد خرید خرده')),
                ('wholesale_min_quantity', models.PositiveIntegerField(default=7, verbose_name='حداقل تعداد خرید عمده')),
                ('wholesale_max_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد خرید عمده')),
                ('wholesale_package_size', models.PositiveIntegerField(default=10, verbose_name='اندازه بسته عمده')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('categories', models.ManyToManyField(related_name='products', to='catalog.category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['name'],
            },
        ),
    ]
